### PR TITLE
(WIP) Compile on a Mac

### PR DESCRIPTION
**Pull request by torntrousers**
Update build so it works on a Mac

(it doesn't work yet so more changes still to be added to this pull...)

### CODE REVIEW

**Comment by torntrousers** [comment]
Mac's don't have ```arecord```, apparently it could use ```sox``` instead (eg https://developer.ibm.com/answers/questions/351655/what-are-the-osx-sox-args-equivalent-to-linux-arec/) but I've not been able to get that to work yet.

**Comment by yodakohl** [comment]
If you give me a day I can make a cross-platform recorder based on python-sounddevice.

**Comment by yodakohl** [comment]
Finished it a bit faster. 
Import the AudiostreamSource from cross_record instead of record.
` from cross_record import AudiostreamSource`

 Follow the instructions for installing pyaudio https://people.csail.mit.edu/hubert/pyaudio/

**Comment by torntrousers** [comment]
I can't find ```cross_record```?

**Comment by yodakohl** [comment]
Sorry this file here: https://github.com/nyumaya/nyumaya_audio_recognition/blob/master/python/cross_record.py

**Comment by torntrousers** [comment]
Thanks so much, it works on a Mac now and I have the examples running. I'll do another PR with the updates for that.

**Pull request merged**
